name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: transfer.tex
      - name: Create artifact
        if: contains(github.event.commits[0].message, '[pdf]') == true
        uses: actions/upload-artifact@master
        with:
          name: report
          path: /home/runner/work/transferReport/transferReport/transfer.pdf
